apiVersion: apps/v1
kind: Deployment
metadata:
  name: petsite-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: petsite
  replicas: 2
  template:
    metadata:
      labels:
        app: petsite
    spec:
      serviceAccountName: my-sa-ssmfullaccess
      containers:
      - image: awsimaya/petsite:latest
        imagePullPolicy: Always
        name: petsite
        ports:
        - containerPort: 80
          protocol: TCP
        env:
          - name: AWS_XRAY_DAEMON_ADDRESS
            value: xray-service.default:2000