apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: petsite
  region: ${AWS_REGION}

managedNodeGroups:
- name: nodegroup
  desiredCapacity: 2
  iam:
    withAddonPolicies:
      albIngress: true

secretsEncryption:
  keyARN: ${MASTER_ARN}