apiVersion: apps/v1
kind: Deployment
metadata:
  name: petsite
  labels:
    app: petsite
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petsite
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: petsite
    spec:
      containers:
      - image: 831210339789.dkr.ecr.us-east-1.amazonaws.com/petsite:latest
        imagePullPolicy: Always
        name: petsite
        ports:
        - containerPort: 80
          protocol: TCP
        env:
        - name: SEARCH_URL
          value: "http://PetAdoption-SearchAPI-366419696.us-east-1.elb.amazonaws.com/api/search?{searchUri}"
        - name: PAYMENT_URL
          value: "http://payforadoptions-542584011.us-east-1.elb.amazonaws.com/api/home/CompleteAdoption?petId={petId}"
        - name: QUEUE_URL
          value: "https://sqs.us-east-1.amazonaws.com/831210339789/PetAdoptions"
